// Auto-generated by the generator
// Don't manually edit this file

// @flow

import type {Action} from '../../types'
import type {HomeworkState} from '../types'

import {initialState} from './initialState'

export const homeworkReducer = (state: HomeworkState = initialState, action: Action<any>): HomeworkState => {
  switch (action.type) {
    default:
      return state
  }
}
