// Auto-generated by the generator
// Don't manually edit this file

// @flow

import {getGroupWorkList} from './getGroupWorkList'
import {getGroupHomeworkList} from './getGroupHomeworkList'
import {getGroupWork} from './getGroupWork'

export const groupWorkSelectors = {
  getGroupWorkList,
  getGroupHomeworkList,
  getGroupWork,
}
