// Auto-generated by the generator
// Don't manually edit this file

// @flow

import type {Action} from '../../types'
import type {SessionState} from '../types'

import {initialState} from './initialState'

export const sessionReducer = (state: SessionState = initialState, action: Action<any>): SessionState => {
  switch (action.type) {
    default:
      return state
  }
}
