// Auto-generated by the generator
// Don't manually edit this file

// @flow

import {setGroupWorkList} from './setGroupWorkList'
import {goToGroupWork} from './goToGroupWork'
import {setGroupHomeworkList} from './setGroupHomeworkList'

export const groupWorkActions = {
  setGroupWorkList,
  goToGroupWork,
  setGroupHomeworkList,
}
