// Auto-generated by the generator
// Don't manually edit this file

// @flow

import {getHomeworkList} from './getHomeworkList'
import {getGroupHomeworkList} from './getGroupHomeworkList'

export const homeworkSelectors = {
  getHomeworkList,
  getGroupHomeworkList,
}
