// Auto-generated by the generator
// Don't manually edit this file

// @flow

import {getHomeworkList} from './getHomeworkList'
import {getWorkGroupList} from './getWorkGroupList'

export const homeworkSelectors = {
  getHomeworkList,
  getWorkGroupList,
}
