// Auto-generated by the generator
// Don't manually edit this file

// @flow

import {goToGroupWorkEffect} from './goToGroupWork'
import {createGroupHomeworkEffect} from './createGroupHomework'
import {initEffect} from './init'
import {createGroupEffect} from './createGroup'
import {deleteGroupHomeworkEffect} from './deleteGroupHomework'

export const groupWorkEffects = [
  goToGroupWorkEffect,
  createGroupHomeworkEffect,
  initEffect,
  createGroupEffect,
  deleteGroupHomeworkEffect,
]
