// Auto-generated by the generator
// Don't manually edit this file

// @flow

import {goToGroupWorkEffect} from './goToGroupWork'
import {createGroupHomeworkEffect} from './createGroupHomework'

export const groupWorkEffects = [
  goToGroupWorkEffect,
  createGroupHomeworkEffect,
]
