// Auto-generated by the generator
// Don't manually edit this file

// @flow

import {signIn} from './signIn'
import {setUser} from './setUser'

export const sessionActions = {
  signIn,
  setUser,
}
