// Auto-generated by the generator
// Don't manually edit this file

import {createStore, applyMiddleware, compose, combineReducers} from 'redux'
import createSagaMiddleware from 'redux-saga'
import {router5Middleware as createRouterMiddleware, router5Reducer} from 'redux-router5'
import {router} from '../router'
import {initialState} from './initialState'
import {homeworkReducer} from './homework/reducers'
import {homeworkEffects} from './homework/effects'
import {sessionReducer} from './session/reducers'
import {sessionEffects} from './session/effects'
import {groupWorkReducer} from './groupWork/reducers'
import {groupWorkEffects} from './groupWork/effects'

const sagaMiddleware = createSagaMiddleware()
const routerMiddleware = createRouterMiddleware(router)

const composeEnhancers = window.__REDUX_DEVTOOLS_EXTENSION_COMPOSE__ || compose

const store = createStore(
  combineReducers({
    router: router5Reducer,
    homework: homeworkReducer,
    session: sessionReducer,
    groupWork: groupWorkReducer,
  }),
  initialState,
  composeEnhancers(applyMiddleware(
    sagaMiddleware, routerMiddleware
  ))
)

homeworkEffects.forEach(fx => sagaMiddleware.run(fx))
sessionEffects.forEach(fx => sagaMiddleware.run(fx))
groupWorkEffects.forEach(fx => sagaMiddleware.run(fx))

export {
  store
}
