// Auto-generated by the generator
// Don't manually edit this file

// @flow

import type {HomeworkState} from './homework/types'
import type {SessionState} from './session/types'

export type Action<P> = {
  type: string,
  payload: P
}

export type Reducer<S, P> = (state: S, action: Action<P>) => S

export type Effect = Generator<any, any, any>

export type ApplicationState = {
  homework: HomeworkState,
  session: SessionState,
}
