// Auto-generated by the generator
// Don't manually edit this file

// @flow

import {signInEffect} from './signIn'
import {signUpEffect} from './signUp'

export const sessionEffects = [
  signInEffect,
  signUpEffect,
]
