// Auto-generated by the generator
// Don't manually edit this file

// @flow

import {initEffect} from './init'
import {createHomeworkEffect} from './createHomework'

export const homeworkEffects = [
  initEffect,
  createHomeworkEffect,
]
