// Auto-generated by the generator
// Don't manually edit this file

// @flow

import {setHomeworkList} from './setHomeworkList'
import {setWorkGroupList} from './setWorkGroupList'
import {createHomework} from './createHomework'

export const homeworkActions = {
  setHomeworkList,
  setWorkGroupList,
  createHomework,
}
